name: Deploy Serverless

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # Adding other services here (like zinki)
        stage: [revampr]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install NPM dependencies
      run: npm ci
    - name: Compute intermediate env vars
      run: |
        export STAGE_UPPER=$(echo ${{ matrix.stage }} | tr '[a-z]' '[A-Z]');
        echo "STAGE_UPPER=$STAGE_UPPER" >> $GITHUB_ENV
    - name: 'Set deployment environment'
      run: |
        echo "${{ secrets[format('ENV_{0}_YML', env.STAGE_UPPER)] }}" .enc.yml 
        cat .enc.yml | base64 -d > .env.${{ matrix.stage }}.yml

    - name: serverless deploy
      uses: serverless/github-action@v3
      with:
        args: deploy --stage ${{ matrix.stage }}
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        # or if using AWS credentials directly
        # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
